FROM python:3.6
RUN pip install --upgrade pip
workdir /main
COPY . .
RUN apt-get update
RUN apt-get install python-pip -y
RUN pip install -r Docker/requirements.txt
EXPOSE 8000
CMD ["uvicorn","main:app", "--host", "0.0.0.0","--reload"]